name: Validate Gradle Wrapper

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Validate Wrapper
        uses: gradle/actions/wrapper-validation@v6
